name: Build and publish Docker image

on:
  workflow_dispatch:
  pull_request:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Gather build metadata
        id: vars
        run: |
          IMAGE_NAME=${GITHUB_REPOSITORY,,}
          echo "image=${IMAGE_NAME}" >> "$GITHUB_OUTPUT"
          BASE_VERSION=$(node -p "require('./package.json').version")
          BUILD_VERSION="${BASE_VERSION}-${GITHUB_RUN_NUMBER}.${GITHUB_RUN_ATTEMPT}"
          echo "version=${BUILD_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and (optionally) push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
          tags: |
            ${{ env.REGISTRY }}/${{ steps.vars.outputs.image }}:latest
            ${{ env.REGISTRY }}/${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.version }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.version=${{ steps.vars.outputs.version }}
